spring:
    application:
        name: mall
    profiles:
        active: dev
server:
    port: 8080
    tomcat:
        uri-encoding: utf-8
    servlet:
        context-path: /mall

# 参考链接: https://blog.csdn.net/Thinkingcao/article/details/100655581
mybatis-plus:
    #实体扫描，多个package用逗号或者分号分隔
    global-config:
        db-config:
            #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
            id-type: auto
            logic-delete-value: -1
            logic-not-delete-value: 0
        banner: false
    mapper-locations:
        - classpath:mapper/*.xml
        - classpath*:com/**/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        call-setters-on-nulls: true
        jdbc-type-for-null: 'null'
    type-aliases-package: com.yunxi.mall.*.entity


